### ISSUE TITLE
Length needs support Length * TypographicResolution

### ISSUE THREAD

**Issue by ZHZG** [objorke/QuantityTypes#16]
Length needs support Length * TypographicResolution.
For example: (10 * Length.Inch) * (96 * TypographicResolution.DotsPerInch)

**Comment by objorke** [comment]
We already have a TypographicLength * TypographicResolution operator. Maybe the TypographicLength should be removed... Is it correct to use `double` as result type. Or create a new quantity type with unit "dots"?

**Comment by Agbar** [comment]
`TypographicLength` defines `Point` unit. Otherwise it may be redundant - it only carries some special semantics, arguably unimportant. It duplicates several units from `Length` too.
One posible (breaking) change is to move `Point` to `Length` as `TypographicPoint` unit and maybe rename `TypographicResolution` to `Resolution` too. Next minor would be transition version with deprecated `TypographicLength` et al.

Is there any reason `Length * TypographicResolution` is not commutative?

**Comment by objorke** [comment]
All operators should now be covered.
The discussion whether `TypographicLength` and `Length` should be merged, should be in a new issue - or on [gitter](https://gitter.im/objorke/QuantityTypes)!
