### ISSUE TITLE
Units for Concentrations

### ISSUE THREAD

**Issue by cptjazz** [objorke/QuantityTypes#4]
I think it would be neat to add quantities for the several types of concentrations (https://en.wikipedia.org/wiki/Concentration)

I guess some of the new quantities will be aliases (in the way they work and which units they use) of existing quantities (cf. density <-> mass concentration). But introducing new quantities will enable the user to better express the intent.

**Comment by ksheffer-opti** [comment]
I have implemented MassConcentration in #26. We also use some very domain-specific types of concentrations like MassConcentrationInWater (important because 1 kg/m^3 == 1 ppm when the solvent is water) and [VolumetricWaterContent](https://en.wikipedia.org/wiki/Water_content). Would those be appropriate to add to the library or are they not general enough?

**Comment by objorke** [comment]
if water is the only fluid that needs to be implemented, then I think this is general enough. Feel free to add it to the library and create a PR. Should there be implicit conversions to `Fraction`?
I see a need for documentation of all these quantity types now...
